### ISSUE TITLE
[tsc error] unused var of  npm package abi-wan-kanabi

### ISSUE THREAD

**Issue by YanYuanFE** [starknet-io/starknet.js#1249]
**Describe the bug**
When I was using starknet.js, tsc encountered an error. This error came from the npm package abi-wan-kanabi. In order to fix this error, I submitted a PR. If there are maintainers of this library, I hope they can help me. review this PR. thanks. https://github.com/keep-starknet-strange/abi-wan-kanabi/pull/74

**To Reproduce**
Steps to reproduce the behavior
create a vite+react project, use starknetkit and starknet-core/react build dapp, npm run build

**Expected behavior**
build work fine

**Screenshots**
![image](https://github.com/user-attachments/assets/75695d18-6801-43c9-9f33-b10aa4c6fd8f)

**Desktop (please complete the following information):**

- Browser & version [e.g. chrome, safari, webworker]
- Node version [e.g. 16.0.1]
- Starknet.js version 
- Network [devnet, testnet]

"starknet": "^5.24.3",
    "starknetkit": "^1.1.9",
"@starknet-react/core": "^2.2.5",

**Additional context**

**Comment by Immanuelolivia1** [comment]
Hey @YanYuanFE, can i be assigned to work on this ?

**Comment by ivpavici** [comment]
Hello!
To confirm, you are using starknet.js "^5.24.3" ? 
That one is pretty old, did you try with the latest version?

**Comment by YanYuanFE** [comment]
> Hello! To confirm, you are using starknet.js "^5.24.3" ? That one is pretty old, did you try with the latest version?

gm, Because this project has been running online for a long time, we will consider upgrading to a new version later, and it is not a problem with starknet.js.

**Comment by ivpavici** [comment]
ok but Starknet.js comes with Abi-wan as a dependency. 
In such an old version even if the bug exists, it is most likely solved with a new version of both packages (because we didn't have complaints of this type)
Can you try and update and let us know?

**Comment by YanYuanFE** [comment]
> ok but Starknet.js comes with Abi-wan as a dependency. In such an old version even if the bug exists, it is most likely solved with a new version of both packages (because we didn't have complaints of this type) Can you try and update and let us know?

"@starknet-react/core": "^3.0.2",
"starknet": "^6.15.0",
    "starknetkit": "^2.3.3",
I just upgraded these three dependency packages to the latest version. This error still occurred when executing npm run build. The reason why others did not have this problem may be that my tsconfig.json contains the following configuration.
"noUnusedLocals": true,
    "noUnusedParameters": true,

<img width="1251" alt="image" src="https://github.com/user-attachments/assets/f468036e-f1ea-45e0-95f0-d8e02caad1e3">

**Comment by ivpavici** [comment]
ok, thanks! We'll take a look

**Comment by ivpavici** [comment]
@PhilippeR26 can you try and reproduce this issue on your testing dapp? 🙏

**Comment by YanYuanFE** [comment]
> > ok but Starknet.js comes with Abi-wan as a dependency. In such an old version even if the bug exists, it is most likely solved with a new version of both packages (because we didn't have complaints of this type) Can you try and update and let us know?
> 
> "@starknet-react/core": "^3.0.2", "starknet": "^6.15.0", "starknetkit": "^2.3.3", I just upgraded these three dependency packages to the latest version. This error still occurred when executing npm run build. The reason why others did not have this problem may be that my tsconfig.json contains the following configuration. "noUnusedLocals": true, "noUnusedParameters": true,
> 
> <img alt="image" width="1251" src="https://private-user-images.githubusercontent.com/17774285/377815937-f468036e-f1ea-45e0-95f0-d8e02caad1e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjQzOTIsIm5iZiI6MTcyOTI2NDA5MiwicGF0aCI6Ii8xNzc3NDI4NS8zNzc4MTU5MzctZjQ2ODAzNmUtZjFlYS00NWUwLTk1ZjAtZDhlMDJjYWFkMWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE1MDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYjA2ZTgyNmQ1N2VlOWRhNDUwYTcwMDliOWRhMTk0NDE1MjMxZTk3ODdmMzcwY2ZjNGUxZTI5ZTEwYmJjMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gcZeWVSEaHgWWfTd1jpIXw-1XM0Wh4QB1mFt21zv_v4">

I confirmed again. The reason why the build still failed after the upgrade was that one of our dependencies also relied on starknet@5.x. The 5.x version internally relied on abi-wan-kanabi@1.x, which was caused by this version. Error, so I created a new vite+react project. It will report an error when using starknet@5. It will not report an error when upgrading to starknet@6.

**Comment by ivpavici** [comment]
OK, thanks! closing!
